- repo: https://github.com/scrambldchannel/pre-commit-julia
  rev: v0.1.5
  hooks:
    - id: runtests_julia
      files: '\.(jl|JL)$'
      stages: [push]
    - id: format_julia
      files: '\.(jl|JL)$'
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  -   id: check-yaml
      files: '\.(yml|yaml)$'
  -   id: check-toml
      files: '\.(tml|toml)$'