  - repo: https://github.com/scrambldchannel/pre-commit-julia
    rev: v0.1.5
    hooks:
      - id: runtests_julia
        files: '\.(jl|JL)$'
        stages: [push]
      - id: format_julia
        files: '\.(jl|JL)$'