name = "JuliaTM1"
uuid = "77072e5b-be5f-4aad-92ba-c06678f629ad"
authors = ["Alexander Sutcliffe <sutcliffe.alex@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
